### ISSUE TITLE
Image does not download

### ISSUE THREAD

**Issue by pwalczysko** [ome/omero-downloader#36]
The image https://nightshade.openmicroscopy.org/webclient/?show=image-4330619 does not download when downloader is deployed on it.

Strangely, also OMERO.web UI original file download fails.

See the original (different topic) issue reported in https://github.com/ome/omero-iviewer/issues/304

cc @mtbc

**Comment by pwalczysko** [comment]
Interestingly, it also does not export as ome-tiff

```
(base) pwalczysko@ls31618~/Montpellier/OMERO.downloader-0.2.1$ sh download.sh -b /Users/pwalczysko/Montpellier/fresh -s ni......copy.org -u p...ko -w xxxx  -f ome-tiff Image:4330619
finding target images... done
mapping filesets of images... done
(1/1) commencingcaught unexpected exception: java.lang.NoSuchMethodError: java.nio.ByteBuffer.position(I)Ljava/nio/ByteBuffer;
(base) pwalczysko@ls31618~/Montpellier/OMERO.downloader-0.2.1$ 
```

**Comment by mtbc** [comment]
That looks like a different issue related to the artifact packaging. From the source checkout the export runs fine for me.

**Comment by pwalczysko** [comment]
The image has 29 G.

Not sure what to make out of the export failure then ?

**Comment by mtbc** [comment]
Nor I so far. I wonder if it's related to change in dependencies for gateway or something. :man_shrugging: Released artifacts might also be otherwise problematic.

**Comment by mtbc** [comment]
I am afraid that you must download with `-f binary,companion` to work around a bug in Bio-Formats that is confusing about which files are companion files. Be especially suspicious of the formats I list in https://trello.com/c/lJtRpXGZ/515-bug-used-files-getters#comment-5af1adc9a3ad6613ca89bbdf.

I tried the OMERO.downloader-0.2.1 release artifact with both Java 8 and 11 and it seems to be running fine for me today!

**Comment by mtbc** [comment]
(I tried using that same image, also ome-tiff export.)
